server:
  port: 8081
  servlet:
    context-path: /shop
spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/shop-service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true