server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/identity_service }
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "06V6DMoVfwudVBBiMk2SMGYAJZo5MkYYyqqAQbewdunzlRohBvEmDkjMNnqE4g81"
  valid-duaration: 3600 # in second
  refreshable-duaration : 360000 # second