server:
  port: 8082
  servlet:
    context-path: /user
spring:
  application:
    name: user-service
  datasource:
    url: "jdbc:mysql://localhost:3306/user_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    queue:
      name: notification_queue
    exchange:
      name: notification_exchange
    routing:
      key: notification_key