server:
  port: 8081
  servlet:
    context-path: /shop
spring:
  application:
    name: restaurant-service
  datasource:
    url: "jdbc:mysql://localhost:3306/restaurant_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true